### ISSUE TITLE
Readme feedback

### ISSUE THREAD

**Issue by lpww** [mmatongo/toledo#3]
Nice job on the prompt, I'm really liking it! I have a few questions that were not answered in the readme. Maybe they could be answered here and then added to the readme if they seem relevant.

1. A single screenshot at the top of the readme that gives an idea of what it looks like would be useful. Interested people would be drawn into reading the rest of the documentation while uninterested people could quickly move on. 
2. You show screenshots of what the prompt looks like for different git scenarios (untracked file, modified file, etc) but you don't show how it behaves with multiple git scenarios. What would display if I had a modified file and a renamed file, for example? I guess all relevant icons would display but it's unclear.
3. How does the prompt behave outside of a git repo?

**Comment by mmatongo** [comment]
I've updated the readme with some of your recommendations.

**Comment by lpww** [comment]
Thanks, I appreciate that!
